Update deploy workflow to error if subrepo path not found

diff --git a/.github/workflows/deploy-to-vercel.yml b/.github/workflows/deploy-to-vercel.yml
--- a/.github/workflows/deploy-to-vercel.yml
+++ b/.github/workflows/deploy-to-vercel.yml
@@ -91,8 +91,13 @@ jobs:
             done
 
           if [[ -n "$subrepo_directory" ]]; then
+            echo "Entering $subrepo_directory..."
             cd "$subrepo_directory"
+            echo "Checking out $SUBREPO_REF..."
             git checkout "$SUBREPO_REF"
+          else
+            echo "ERROR: Could not find directory for 'https://github.com/mcmire/$SUBREPO_NAME'"
+            exit 1
           fi
         shell: bash
       - uses: actions/setup-node@v6
